name: Update COVID-19 data

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download latest COVID-19 data
        run: |
          git submodule update --init
          git submodule foreach git checkout master
          git submodule foreach git pull
          echo "::set-env name=NEW_DATA::$(git status -s)"

      - name: Commit the new COVID-19 data
        if: ${{ env.NEW_DATA != '' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update COVID-19 data"

      # TODO: run unit/e2e tests?

      - name: Push changes
        if: ${{ env.NEW_DATA != '' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
